version: '2'
services:
    fileparser:
      build:
          context: .
          dockerfile: ./Dockerfile
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
      expose:
        - "3000"
      ports:
        - "8081:3000"
      command: "nodemon start"
      networks:
      - public
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
